#!/bin/bash

set -e

PROJ=biglist
SRC=$(pwd)/src/${PROJ}
TESTS=$(pwd)/tests


echo
echo --- running bandit ---
echo
bandit -r -lll ${SRC}
bandit -r -lll ${TESTS}

echo
echo --- running pyflakes ---
echo
python -m pyflakes ${SRC}
echo
python -m pyflakes ${TESTS}

echo
echo --- running mypy ---
echo
python -m mypy ${SRC} || true

echo
echo --- running pylint ---
echo
python -m pylint --disable=C0103,C0114,C0115,C0116,C0301,C0303,C0305,R0903 ${SRC} || true

